name: Populate buffer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
    fetch:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python ./Bufferer.py write_buffer ${{ secrets.ARG1 }} ${{ secrets.ARG2 }}
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name "da"
          git add ./buffered_feed
          git commit -m "Updated buffered_feed"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
